### ISSUE TITLE
Use tmpfs

### ISSUE THREAD

**Issue by gmarziou** [intesys/generator-jhipster-testcontainers#1]
Hello,

Thanks for this useful module, I think it should be included in the main generator as it is non intrusive due to your use of a spring profile.

What do you think about enabling [tmpfs](https://www.testcontainers.org/modules/databases/#running-container-with-tmpfs-options) ?

Thanks,
Gael

**Comment by ecostanzi** [comment]
@gmarziou I haven't worked on this module for a while and I totally missed this, really sorry for that. 

https://docs.docker.com/storage/tmpfs/#limitations-of-tmpfs-mounts here it seems that the tmpfs is available only for linux. We should add it only when running the tests on linux. Do you have any idea?

About the integration with the mail generator, it has already been discussed here: https://github.com/jhipster/generator-jhipster/issues/10958. I'll try to improve it a little bit and see what the other members think about it.
